### ISSUE TITLE
Apply for `namecheap_record` does not apply and doesn't time out

### ISSUE THREAD

**Issue by NicoleYson** [adamdecaf/terraform-provider-namecheap#16]
### Terraform Version
`Terraform v0.11.13`

### Affected Resource(s)
`namecheap_record`

### Terraform Configuration Files
```
resource "namecheap_record" "subdomain" {
  count   = "${length(var.subdomains)}"
  domain  = "${var.domain}"
  name    = "${element(var.subdomains,count.index)}"
  address = "partners.vacasa.com"
  type    = "CNAME"
}

```

### Debug Output
`Still creating...  (45m31s elapsed)`

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.
No panic, attempting to create for 45 minutes

### Expected Behavior
Either it times out or creates the record

### Actual Behavior
What actually happened?
I tried to apply one `namecheap_record` resource, and has been hanging on `Still creating...` for 45 minutes.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
Are there anything atypical about your accounts that we should know? 

Using a sandbox account, hesitant to try on production.

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
Unsure if this is related-
https://github.com/adamdecaf/terraform-provider-namecheap/issues/13

**Comment by adamdecaf** [comment]
It could be related to #13, but what version of the namecheap provider are you using? I fixed a bug that sounds very similar to yours in 1.2.0.

https://github.com/adamdecaf/terraform-provider-namecheap/releases/tag/1.2.0

**Comment by adamdecaf** [comment]
@NicoleYson Did you figure this out? Need some help?

**Comment by OGProgrammer** [comment]
IP probably isn't whitelisted but I do have concerns with how slow this is. We should contact Namecheap about the throttling and work with them on a way to fix/raise that. I have not been hitting the Retry parts but I am managing 30+ domains with this and watching terraform build the apply/plan seems to fetch domain info serially. Perhaps we can async these calls within reason (under whatever Namecheap comes back as us with). You could argue I shouldn't use it for so many domains but with route_53 I bet it would be way faster than this. It still gets the job done, just have a feeling there is room for improvement somewhere still. Do you work at Namecheap @adamdecaf or know someone?

**Comment by adamdecaf** [comment]
I don't work at Namecheap and don't know anyone who does. IIRC their API didn't handle concurrent requests. Maybe they have a newer API that does?

What version are you on? I [lowered the retry sleep interval](https://github.com/adamdecaf/terraform-provider-namecheap/commit/74a1f5143795c9b01337276c8f4dd62182d58f0f), which helped speed up applys after an error. I can make a RC version to try -- it'll be on Terraform 0.12 though.

**Comment by NicoleYson** [comment]
Oops sorry, I missed these notifications!

I was using the latest version at that time, but I am no longer using this provider because of this bug. 

I was using a combination of 
```
data "http" "host_ip" {
  url = "https://ipv4.icanhazip.com"
}
``` 
and `${chomp(data.http.host_ip.body)}` to get the ip and I ensured I whitelisted the relevant IP in namecheap as well.

**Comment by adamdecaf** [comment]
Okay, sounds like the performance is definitely an issue. I hope the next release, which upgrades to Terraform 0.12 when Hashicorp releases it, will be faster for everyone.

**Comment by adamdecaf** [comment]
1.3.0 of this provide has been released. Does that improve the performance for you at all?

**Comment by OGProgrammer** [comment]
Def see an improvement , thanks adam

**Comment by adamdecaf** [comment]
Thanks. Feel free to ping this issue or open a new one with other problems.

**Comment by cu12** [comment]
Sorry to reopen, but this also could be due to the amount of DNS records you are trying to add, limit is 150.

Error on the interface, looks like this, when you reached the limit:
```
Error occured: Too many host records, not supported by DNS System V2. Maximum number of records supported by DNS System V2 is 150. Please delete the extra records from All Host Records page and try again.
```
