### ISSUE TITLE
Please release new version of provider with the support of ALIAS records

### ISSUE THREAD

**Issue by JohnnyMastricht** [adamdecaf/terraform-provider-namecheap#27]
Hi there! I see that Go library for Namecheap API was updated and now includes the support of ALIAS records. Could you please be so kind to release new version of provider for that?

Thanks in advance

**Comment by adamdecaf** [comment]
I've released 1.5.0

https://github.com/adamdecaf/terraform-provider-namecheap/releases/tag/1.5.0
