### ISSUE TITLE
tf 0.13

### ISSUE THREAD

**Issue by orefalo** [adamdecaf/terraform-provider-namecheap#34]
Error: Failed to install provider

Error while installing hashicorp/namecheap: provider registry
registry.terraform.io does not have a provider named
registry.terraform.io/hashicorp/namecheap

**Comment by orefalo** [comment]
https://www.terraform.io/upgrade-guides/0-13.html

look like it's just configuration - testing

**Comment by orefalo** [comment]
ok, so first - it appears this repository must be renamed.
from terraform-provider-namecheap to namecheap

next, you need to register it on https://registry.terraform.io/

**Comment by romanoff** [comment]
There seems to be updated documentation for in-house providers here: https://www.terraform.io/upgrade-guides/0-13.html#in-house-providers . But I wasn't successful in following provided steps. If somebody will be more lucky, please provide your steps. Also would be great if this provided was in general registry so that additional steps were not required to get it working

**Comment by adamdecaf** [comment]
I didn't know Terraform 0.13 changes how providers are distributed, but I can see about adding it to the official registry. I doubt I'll get to doing that this week. I don't think the repository needs renamed - `terraform-provider-zzzz` has been the standard for years.

**Comment by andreyvital** [comment]
Any updates @adamdecaf? 🤓

**Comment by orefalo** [comment]
As a reference, here is link to another extension I use. They had to publish the extension to get it working with tf 13 -

Please let us know if you want to handle this (I would recommend since you are the author) or if you want someone else to own this deployment type.

https://github.com/banzaicloud/terraform-provider-k8s/issues/6

**Comment by dcordz** [comment]
I was able to get this working by "faking" the hashicorp registry in the ~/.terraform.d/plugins directory

Instead of using the target directory/instructions in the readme I did (on my mac):

```
mkdir -p ~/.terraform.d/plugins/registry.terraform.io/hashicorp/namecheap/1.5.0/darwin_amd64

curl -L https://github.com/adamdecaf/terraform-provider-namecheap/releases/download/1.5.0/terraform-provider-namecheap-osx-amd64 > ~/.terraform.d/plugins/registry.terraform.io/hashicorp/namecheap/1.5.0/darwin_amd64/terraform-provider-namecheap_v1.5.0

chmod +x ~/.terraform.d/plugins/registry.terraform.io/hashicorp/namecheap/1.5.0/darwin_amd64/terraform-provider-namecheap_v1.5.0
```

Add the provider to terraform in <root_dir>/versions.tf:
```terraform {
  required_version = ">= 0.13"
  required_providers {
    namecheap = {
      version  = "~> 1.5.0"
    }
  }
}
```

Instantiate the provider in <root_dir>/main.tf:
```provider "namecheap" {
  username = var.namecheap_username
  api_user = var.namecheap_api_user
  token    = var.namecheap_api_token
  ip       = var.namecheap_ip_address
}```

Create the resource:
```resource "namecheap_record" "my_record" {
  name    = var.name
  domain  = var.domain
  address = var.address
  type    = var.type
}```

**Comment by draganm** [comment]
@dcordz you can use provider shims: https://numtide.com/articles/generate-terraform-provider-shim/

Unfortunately current version of the shim generator won't work with this repository (expects release files to be either in a `.tar.gz` or `.zip` archive), but you can easily create a shim bash script by changing the example from the article a bit and check it in with the rest of the terraform code.

**Comment by kerberjg** [comment]
@dcordz @draganm These are both good solutions, but they don't seem to work with Terraform Cloud

**Comment by adamdecaf** [comment]
I'm going to look at updating this provider over the weekend.

**Comment by dovidgef** [comment]
Hi, I was only able to use the namecheap provider using @dcordz trick.
Perhaps add this trick to the Readme instructions.

Thanks for all your hard work.

**Comment by orefalo** [comment]
I can confirm the trick worked for me too. It should be added to the instructions.

With that said, I got tired of registering my IP with namecheap for API Access, and switched to the hertzner DNS. the terraform provider works like a charm and it is registered on hashycorp repo.

**Comment by b-m-f** [comment]
Here is another solution:
# Specify provider
Create versions.tf:

```
terraform {
  required_providers {
    namecheap = {
      source  = "registry.local/github/namecheap"
      version = "1.5.0"
    }
  }
}
```
# Install module to new local registry folder
Now install the module to `` with:
```
wget -O ~/.terraform.d/plugins/registry.local/github/namecheap_v1.5.0 https://github.com/adamdecaf/terraform-provider-namecheap/releases/download/1.5.0/terraform-provider-namecheap-linux-amd64
```  

# Update state
For the state to use the correct module run:
```
terraform state replace-provider 'registry.terraform.io/-/namecheap' 'registry.local/github/namecheap'
```

If you had the hack from @dcordz applied run:
```
terraform state replace-provider 'registry.terraform.io/hashicorp/namecheap' 'registry.local/github/namecheap'
```

# More info
https://www.terraform.io/upgrade-guides/0-13.html#in-house-providers
