### ISSUE TITLE
Record gets created but terraform apply times out on Creating.

### ISSUE THREAD

**Issue by OGProgrammer** [adamdecaf/terraform-provider-namecheap#7]
### Terraform Version
Terraform v0.11.10
v1.0.0 Release for Namecheap provider on osx

### Affected Resource(s)
namecheap_record

### Debug Output
None provided after TF_LOG=info defined..

### Expected Behavior
Apply completes

### Actual Behavior
Keeps trying to create the record even though it creates the record. It is like it doesn't get back a response that the apply was successful. 

### Output
```
namecheap_record.remotedevforce-com-mx2: Still creating... (20s elapsed)
namecheap_record.remotedevforce-com-mx1: Still creating... (20s elapsed)
namecheap_record.remotedevforce-com-dkim: Still creating... (20s elapsed)
...
namecheap_record.remotedevforce-com-mx2: Still creating... (30m30s elapsed)
namecheap_record.remotedevforce-com-mx1: Still creating... (30m30s elapsed)
namecheap_record.remotedevforce-com-dkim: Still creating... (30m30s elapsed)
```

### Steps to Reproduce
1. `terraform apply`

**Comment by OGProgrammer** [comment]
I'm on the new mac osx Mohave update 10.14.1

**Comment by OGProgrammer** [comment]
To clarify, it creates the record in namecheap. However, the terraform apply never gets a response back I guess that it was created...

**Comment by adamdecaf** [comment]
I recall running into this recently. I'll take a look.

**Comment by OGProgrammer** [comment]
Tried building master and using my compiled provider but no luck. Disabled 2FA and tried refreshing my API key. No luck still, same behavior.

**Comment by OGProgrammer** [comment]
Added trace level, was at info only. Still nothing 100% but maybe some of this you might recognize...
```

2018/12/03 21:34:09 [TRACE] dag/walk: vertex "provider.namecheap (close)", waiting for: "namecheap_record.test-remotedevforce-com"
2018/12/03 21:34:09 [TRACE] dag/walk: vertex "meta.count-boundary (count boundary fixup)", waiting for: "namecheap_record.test-remotedevforce-com"
2018/12/03 21:34:09 [TRACE] dag/walk: vertex "root", waiting for: "meta.count-boundary (count boundary fixup)"
2018/12/03 21:34:14 [TRACE] dag/walk: vertex "meta.count-boundary (count boundary fixup)", waiting for: "namecheap_record.test-remotedevforce-com"
2018/12/03 21:34:14 [TRACE] dag/walk: vertex "provider.namecheap (close)", waiting for: "namecheap_record.test-remotedevforce-com"
2018/12/03 21:34:14 [TRACE] dag/walk: vertex "root", waiting for: "meta.count-boundary (count boundary fixup)"
```

Really want to use the provider and stop doing that stuff manually haha.

**Comment by adamdecaf** [comment]
If you `C-c` and `terraform plan` does Terraform want to still create the record?

**Comment by adamdecaf** [comment]
@OGProgrammer Fixed the bug. It was bad `sync.Mutex` calls. The fix ihttps://github.com/adamdecaf/terraform-provider-namecheap/commit/e6e2bfb39d22f4385907fda07c363f0aa7a330fd 

I'm cutting a release now.

**Comment by OGProgrammer** [comment]
You are a god among men, Thanks Adam.
